name: CI devops 2024
on:
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean install --file API/simpleapi/pom.xml -B
  
  # define job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend
  # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      sDOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

  # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Login to Docker Hub
      - name: Login to DockerHub
        run: echo "$DOCKERHUB_USERNAME" | docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
        shell: bash

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./API/simpleapi
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./postgres
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
        # relative path to the place where source code with Dockerfile is located
          context: ./http-server
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-httpd:latest
          

